let horror = [
    {
        title: 'the ring',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'saw',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'jaws',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'orphan',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'annabelle',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'paranormal activity',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'saw',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'the counjouring',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
]