let hp =[
    {
        title: 'the philosophers stone',
        drink: 'butterbeer',
        main: 'pumpkin pasties & chicken drumsticks',
        snack: 'chocolate frogs',
        desset: 'bithday cake',
    },
    {
        title: 'the champer of secrets',
        drink: 'polyjuice potion',
        main: 'mollys refilling sandwhiches',
        snack: 'berty botts',
        desset: 'petunias dessert',
    },
    {
        title: 'the prisoner of azkaban',
        drink: 'pumpkin juice',
        main: 'steak and kidney pudding',
        snack: 'acid pops',
        desset: 'bath bun',
    },
    {
        title: 'the goblet of fire',
        drink: 'firewhiskey',
        main: 'bouillabaisse',
        snack: 'canary creams',
        desset: 'cauldron cakes',
    },
    {
        title: 'the order of the pheonix',
        drink: 'iced dandelion juice',
        main: 'sherpherd pie',
        snack: 'sciving snackbox',
        desset: 'treacle tart',
    },
    {
        title: 'the half blood prince',
        drink: 'mead',
        main: 'onion soup',
        snack: 'rock cake',
        desset: 'egg nog',
    },
    {
        title: 'the deathly hallows: part 1',
        drink: 'champange',
        main: 'sandwiches',
        snack: 'berries',
        desset: 'snitch cake',
    },
    {
        title: 'the deathly hallows: part 2',
        drink: 'butterbeer',
        main: 'spag bol',
        snack: 'licorice wands',
        desset: 'treacle tart',
    }
]

let disney = [
    {
        title: 'mulan',
        drink: 'tea',
        main: 'smiley congee',
        snack: 'dumplings',
        desset: '',
    },
    {
        title: 'frozen',
        drink: 'hot chocolate',
        main: 'fondue',
        snack: 'snowball cake pops',
        desset: 'olaf floating in jello',
    },
    {
        title: 'brave',
        drink: 'beer',
        main: 'drumsticks and scotch eggs',
        snack: 'iced buns',
        desset: 'spell cake',
    },
    {
        title: 'snow white',
        drink: 'apple cider',
        main: 'potato and sausage soup',
        snack: 'carmel apples',
        desset: 'grumpy pie',
    },
    {
        title: 'princess and the frog',
        drink: 'champagne',
        main: 'gumbo',
        snack: 'gummy frogs',
        desset: 'bingets',
    },
    {
        title: 'tangled',
        drink: 'magic flower cocktail',
        main: 'hazelnut soup',
        snack: 'cookies',
        desset: 'braid eclairs',
    },
    {
        title: 'alice in wonderland',
        drink: 'strawberry lemonade',
        main: 'tea sandwiches',
        snack: 'eat me cakes',
        desset: 'cherry tarts',
    },
    {
        title: 'beauty and the beast',
        drink: 'wine',
        main: 'charcuteire',
        snack: 'macarons',
        desset: 'be our guest deserts',
    },
]

let pixar = [
    {
        title: 'luca',
        drink: '',
        main: 'pasta',
        snack: '',
        desset: '',
    },
    {
        title: 'coco',
        drink: 'margeritas',
        main: 'tacos',
        snack: 'tortilas',
        desset: '',
    },
    {
        title: 'up',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'toy story',
        drink: '',
        main: 'planet pizza',
        snack: 'alien cupcakes',
        desset: '',
    },
    {
        title: 'monsters inc',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'ratatoullie',
        drink: '',
        main: 'rataouille',
        snack: '',
        desset: '',
    },
    {
        title: 'incredibles',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'onward',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'big hero 6',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
]

let marvel = [
    {
        title: 'thor',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'spiderman',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'deadpool',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'blackpanther',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'avengers',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'gaudardians of the galaxy',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'x-men',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'hulk',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'iron-man',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
]

let horror = [
    {
        title: 'the ring',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'saw',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'jaws',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'orphan',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'annabelle',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'paranormal activity',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'saw',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'the counjouring',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
]

let musical = [
    {
        title: 'grease',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'rent',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'les miserable',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'westside story',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'sound of music',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'the greatest showman',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'hair',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
    {
        title: 'oliver',
        drink: '',
        main: '',
        snack: '',
        desset: '',
    },
]